FROM node:22-alpine

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install --production

# Copy source code
COPY . .

# Expose port 4000
EXPOSE 4000

CMD ["node", "src/server.js"]
