/**
 * Test for lib/generatePDF.ts — localised PDF receipt generation (Issue #44).
 *
 * We mock jsPDF and autoTable to avoid actual PDF generation in the test
 * runner, and verify that the i18n integration is wired correctly.
 */

import { generatePDFReceipt, isPDFLocaleRTL, toBCP47 } from "@/lib/generatePDF";

// ---- Mock jsPDF and autoTable ----
const mockDoc = {
  setFillColor: jest.fn(),
  rect: jest.fn(),
  setTextColor: jest.fn(),
  setFontSize: jest.fn(),
  setFont: jest.fn(),
  text: jest.fn(),
  setDrawColor: jest.fn(),
  line: jest.fn(),
  setR2L: jest.fn(),
  save: jest.fn(),
};

jest.mock("jspdf", () => {
  return jest.fn(() => mockDoc);
});

jest.mock("jspdf-autotable", () => jest.fn());

// ---- Mock i18n ----
const mockT = jest.fn((key: string) => {
  const map: Record<string, string> = {
    "receipt.transactionReceipt": "Transaction Receipt",
    "receipt.transactionDetails": "Transaction Details",
    "receipt.confirmed": "CONFIRMED",
    "receipt.failed": "FAILED",
    "receipt.amount": "Amount",
    "receipt.transactionHash": "Transaction Hash",
    "receipt.timestamp": "Timestamp",
    "receipt.ledger": "Ledger",
    "receipt.feeCharged": "Fee Charged",
    "receipt.from": "From",
    "receipt.to": "To",
    "receipt.memo": "Memo",
    "receipt.generatedBy": "Generated by Finchippay",
    "receipt.officialNotice":
      "This is an official transaction receipt from the Stellar blockchain.",
  };
  return map[key] || key;
});

jest.mock("@/lib/i18n", () => ({
  __esModule: true,
  default: {
    t: (key: string) => mockT(key),
  },
  getCurrentLanguage: () => "en",
}));

// ---- Mock formatDate/intlFormat ----
jest.mock("@/utils/intlFormat", () => ({
  formatDate: jest.fn(() => "Jan 1, 2026 · 12:00"),
  formatNumber: jest.fn(() => "1,234"),
}));

// ---- Mock formatAsset ----
jest.mock("@/utils/format", () => ({
  formatAsset: jest.fn(() => "100 XLM"),
}));

describe("generatePDFReceipt (Issue #44 — Multi-Language PDF Receipts)", () => {
  const mockTransaction = {
    hash: "abc123def456",
    ledger: 1234,
    createdAt: "2026-01-01T12:00:00Z",
    sourceAccount: "GABC123...",
    fee: "0.00001",
    amount: "100",
    asset: "XLM",
    from: "GA...FROM",
    to: "GA...TO",
    memo: "Test payment",
    successful: true,
  };

  beforeEach(() => {
    jest.clearAllMocks();
  });

  it("generates a PDF for a successful transaction", async () => {
    await generatePDFReceipt(mockTransaction);

    expect(mockDoc.setFillColor).toHaveBeenCalled();
    expect(mockDoc.rect).toHaveBeenCalled();
    expect(mockDoc.text).toHaveBeenCalled();
    expect(mockDoc.save).toHaveBeenCalled();
    expect(mockDoc.save).toHaveBeenCalledWith(
      expect.stringContaining("finchippay-receipt-abc123de"),
    );

    // Verify i18n keys were used
    expect(mockT).toHaveBeenCalledWith("receipt.transactionReceipt");
    expect(mockT).toHaveBeenCalledWith("receipt.transactionDetails");
    expect(mockT).toHaveBeenCalledWith("receipt.confirmed");
    expect(mockT).toHaveBeenCalledWith("receipt.generatedBy");
    expect(mockT).toHaveBeenCalledWith("receipt.officialNotice");
  });

  it("generates a PDF for a failed transaction", async () => {
    await generatePDFReceipt({
      ...mockTransaction,
      successful: false,
    });

    expect(mockT).toHaveBeenCalledWith("receipt.failed");
    expect(mockT).not.toHaveBeenCalledWith("receipt.confirmed");
  });

  it("does not include amount section when amount is missing", async () => {
    await generatePDFReceipt({
      ...mockTransaction,
      amount: undefined,
      asset: undefined,
    });

    // "Amount" should not be rendered
    const amountCalls = mockT.mock.calls.filter(
      ([key]: string[]) => key === "receipt.amount",
    );
    expect(amountCalls).toHaveLength(0);
  });

  it("writes all table labels", async () => {
    await generatePDFReceipt(mockTransaction);

    expect(mockT).toHaveBeenCalledWith("receipt.transactionHash");
    expect(mockT).toHaveBeenCalledWith("receipt.timestamp");
    expect(mockT).toHaveBeenCalledWith("receipt.ledger");
    expect(mockT).toHaveBeenCalledWith("receipt.feeCharged");
    expect(mockT).toHaveBeenCalledWith("receipt.from");
    expect(mockT).toHaveBeenCalledWith("receipt.to");
    expect(mockT).toHaveBeenCalledWith("receipt.memo");
  });
});

describe("isPDFLocaleRTL", () => {
  it("returns true for Arabic and Hebrew", () => {
    expect(isPDFLocaleRTL("ar")).toBe(true);
    expect(isPDFLocaleRTL("he")).toBe(true);
  });

  it("returns false for LTR languages", () => {
    expect(isPDFLocaleRTL("en")).toBe(false);
    expect(isPDFLocaleRTL("es")).toBe(false);
    expect(isPDFLocaleRTL("fr")).toBe(false);
  });
});

describe("toBCP47", () => {
  it("maps all supported locales to BCP-47 tags", () => {
    expect(toBCP47("en")).toBe("en-US");
    expect(toBCP47("es")).toBe("es-ES");
    expect(toBCP47("fr")).toBe("fr-FR");
    expect(toBCP47("ar")).toBe("ar-SA");
    expect(toBCP47("he")).toBe("he-IL");
  });

  it("falls back to en-US for unknown locales", () => {
    expect(toBCP47("de")).toBe("en-US");
  });
});