/**
 * @finchippay/sdk — Auto-generated types from the Finchippay OpenAPI spec.
 *
 * This file is generated by `npm run generate:sdk` (openapi-typescript).
 * Do not edit this file directly — edit the OpenAPI spec (backend/src/swagger.js)
 * and regenerate.
 */

/* ─── Shared response wrappers ─── */

export interface SuccessResponse<T = unknown> {
  success: boolean;
  data: T;
}

export interface ApiError {
  error: string;
}

/* ─── Schemas ─── */

export interface PaymentRecord {
  id: string;
  type: "sent" | "received";
  amount: string;
  asset: string;
  from: string;
  to: string;
  memo?: string;
  createdAt: string;
  transactionHash: string;
  pagingToken: string;
}

export interface PaymentStats {
  publicKey: string;
  totalSentXLM: string;
  totalReceivedXLM: string;
  sentCount: number;
  receivedCount: number;
  totalTransactions: number;
}

export interface AnalyticsSummary {
  publicKey: string;
  totalSentXLM: string;
  totalReceivedXLM: string;
  sentCount: number;
  receivedCount: number;
  totalTransactions: number;
}

export interface TopRecipient {
  publicKey: string;
  totalXLM: string;
  count: number;
}

export interface ActivityDay {
  date: string;
  totalXLM: string;
  count: number;
}

export interface AccountBalance {
  assetCode: string;
  balance: string;
  asset_type: string;
}

export interface AccountInfo {
  publicKey: string;
  sequence: string;
  balances: AccountBalance[];
  subentryCount: number;
}

export interface Tip {
  id: string;
  from: string;
  to: string;
  amount: string;
  memo?: string;
  createdAt: string;
  transactionHash: string;
}

export interface TipStats {
  totalReceived?: string;
  totalTips?: number;
  totalCount?: number;
  averageAmount?: string;
  averageTip?: string | null;
  largestTip?: string | null;
  smallestTip?: string | null;
  totalByAsset?: Record<string, { count: number; amount: string }>;
}

export interface TxFunctionChallengeRequest {
  ownerPublicKey: string;
  type: "dca" | "stop_loss" | "escrow_release";
  config: Record<string, unknown>;
}

export interface TxFunctionChallengeResponse {
  challengeXDR: string;
  deploymentHash: string;
  normalizedConfig: Record<string, unknown>;
  networkPassphrase: string;
}

export interface TxFunctionDeployRequest {
  ownerPublicKey: string;
  type: "dca" | "stop_loss" | "escrow_release";
  config: Record<string, unknown>;
  deploymentHash: string;
  signedChallengeXDR: string;
}

export interface TxFunctionDeployment {
  id: string;
  ownerPublicKey: string;
  type: "dca" | "stop_loss" | "escrow_release";
  status: "active" | "paused" | "completed";
  config: Record<string, unknown>;
  deploymentHash: string;
  createdAt: string;
  nextRunAt: string | null;
  lastExecutedAt: string | null;
  lastCheckedAt: string | null;
  lastObservedPriceUsd: number | null;
  lastError: string | null;
}

export interface ScheduledTransaction {
  id: number;
  submitAt: string;
  publicKey: string;
  attempts: number;
  createdAt: string;
}

export interface Sep24InitiateRequest {
  asset_code: string;
  account: string;
  memo?: string;
  memo_type?: "text" | "id" | "hash";
  anchor_url?: string;
}

export interface Sep24InteractiveResponse {
  type: "interactive_customer_info_needed";
  url: string;
  id: string;
}

export interface Sep24Transaction {
  id: string;
  kind: "deposit" | "withdrawal";
  status: "pending_external" | "completed" | "error";
  status_eta: number | null;
  more_info_url: string | null;
  amount_in: string | null;
  amount_out: string | null;
  amount_fee: string | null;
  started_at: string;
  updated_at: string;
  completed_at: string | null;
  stellar_transaction_id: string | null;
  external_transaction_id: string | null;
  message: string | null;
}

/* ─── SEP-0012 ─── */

export interface Sep12StatusResponse {
  status: string;
  message?: string | null;
}

export interface Sep12CustomerResponse {
  publicKey: string;
  anchorName: string;
  status: string;
  fields?: Record<string, unknown>;
  message?: string | null;
}

export interface ExecutionLogEntry {
  id: string;
  deploymentId: string;
  status: "created" | "executed" | "error" | "status";
  message: string;
  result: Record<string, unknown> | null;
  createdAt: string;
}

/* ─── Health ─── */

export interface HealthStatus {
  status: string;
  timestamp: string;
}

/* ─── Auth ─── */

export interface ChallengeResponse {
  transaction: string;
  networkPassphrase?: string;
}

export interface TokenResponse {
  token: string;
  accessToken: string;
  refreshToken: string;
}

export interface AuthRequest {
  transaction: string;
}

export interface RefreshTokenRequest {
  refreshToken: string;
}

export interface RevokeSessionRequest {
  sessionId?: number | string;
  refreshToken?: string;
  all?: boolean;
}

export interface SessionInfo {
  id: number;
  publicKey: string;
  deviceInfo?: string;
  ipAddress?: string;
  createdAt: string;
  lastUsedAt?: string;
  expiresAt: string;
}

export interface SessionsResponse {
  success: boolean;
  sessions: SessionInfo[];
}

/* ─── Parse Payment ─── */

export interface ParsePaymentRequest {
  input: string;
}

export interface ParsePaymentResponse {
  amount: string;
  recipient: string;
  memo: string;
  isValid: boolean;
  clarification: string;
}

/* ─── Schedule Transaction ─── */

export interface ScheduleTransactionRequest {
  signedXDR: string;
  submitAt: string;
  publicKey: string;
}

/* ─── Federation ─── */

export interface FederationRecord {
  stellar_address: string;
  account_id: string;
}

/* ─── Username Registration ─── */

export interface RegisterUsernameRequest {
  publicKey: string;
  username: string;
}

export interface ResolveUsernameResponse {
  publicKey: string;
  username: string;
}

/* ─── Polling parameters for payments ─── */

export interface PaymentHistoryParams {
  limit?: number;
  cursor?: string;
}

/* ─── Balance response ─── */

export interface BalanceResponse {
  balance: string;
}

/* ─── Tip creation ─── */

export interface CreateTipRequest {
  from?: string;
  senderPublicKey?: string;
  to?: string;
  creatorPublicKey?: string;
  amount: string;
  asset?: string;
  memo?: string;
  transactionHash?: string;
  txHash?: string;
}

/* ─── Events ─── */

export interface EventsStatsResponse {
  totalEvents: number;
  [key: string]: unknown;
}

export interface TopRecipientsResponse {
  topRecipients: TopRecipient[];
}

/* ─── Pagination / listing ─── */

export interface TurretListParams {
  ownerPublicKey?: string;
}