#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
SDK_DIR="$PROJECT_DIR/sdk"
BACKEND_DIR="$PROJECT_DIR/backend"
TMP_DIR="$(mktemp -d)"
trap 'rm -rf "$TMP_DIR"' EXIT

# Generate the spec JSON from the swagger module without starting a server.
echo "==> Extracting OpenAPI spec from backend/src/swagger.js ..."
node -e "
  const spec = require('${BACKEND_DIR}/src/swagger');
  require('fs').writeFileSync('${TMP_DIR}/spec.json', JSON.stringify(spec, null, 2));
"

if [ ! -s "$TMP_DIR/spec.json" ]; then
  echo "ERROR: Failed to generate OpenAPI spec from backend/src/swagger.js"
  exit 1
fi

# Generate types from the local spec file.
npx --yes openapi-typescript "$TMP_DIR/spec.json" -o "$TMP_DIR/generated.ts"

# Prepend the same header used by generate-sdk.sh.
HEADER="/**
 * @finchippay/sdk — Auto-generated types from the Finchippay OpenAPI spec.
 *
 * This file is generated by \`npm run generate:sdk\` (openapi-typescript).
 * Do not edit this file directly — edit the OpenAPI spec (backend/src/swagger.js)
 * and regenerate.
 */"

if ! head -1 "$TMP_DIR/generated.ts" | grep -q "finchippay"; then
  TMP_FILE=$(mktemp)
  echo "$HEADER" > "$TMP_FILE"
  echo "" >> "$TMP_FILE"
  cat "$TMP_DIR/generated.ts" >> "$TMP_FILE"
  mv "$TMP_FILE" "$TMP_DIR/generated.ts"
fi

# Append the same hand-written aliases that generate-sdk.sh appends.
if [ -f "$SDK_DIR/src/types.aliases.ts" ]; then
  echo "" >> "$TMP_DIR/generated.ts"
  cat "$SDK_DIR/src/types.aliases.ts" >> "$TMP_DIR/generated.ts"
fi

if ! cmp -s "$TMP_DIR/generated.ts" "$SDK_DIR/src/types.ts"; then
  echo "ERROR: SDK types are out of date."
  echo "Run 'npm run generate:sdk' and commit the updated sdk/src/types.ts file."
  diff "$TMP_DIR/generated.ts" "$SDK_DIR/src/types.ts" || true
  exit 1
fi

echo "SDK type generation is up to date."
