#!/usr/bin/env bash
#
# scripts/generate-sdk.sh
# Regenerates the TypeScript SDK types from the backend's OpenAPI spec.
#
# Extracts the spec directly from backend/src/swagger.js (no live server
# needed) so it works reliably in CI and local environments alike.
#
# Usage:
#   ./scripts/generate-sdk.sh
#
# Prerequisites:
#   - Backend dependencies must be installed (cd backend && npm ci)
#   - openapi-typescript must be installed (via root or npx)
#

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
SDK_DIR="$PROJECT_DIR/sdk"
BACKEND_DIR="$PROJECT_DIR/backend"
TMP_DIR="$(mktemp -d)"
trap 'rm -rf "$TMP_DIR"' EXIT

echo "==> Extracting OpenAPI spec from backend/src/swagger.js ..."

# Generate the spec JSON from the swagger module without starting a server.
# This works because swagger-jsdoc builds the spec from JSDoc comments in
# route files — no network or live process is required.
node -e "
  const spec = require('${BACKEND_DIR}/src/swagger');
  require('fs').writeFileSync('${TMP_DIR}/spec.json', JSON.stringify(spec, null, 2));
"

if [ ! -s "$TMP_DIR/spec.json" ]; then
  echo "ERROR: Failed to generate OpenAPI spec from backend/src/swagger.js"
  exit 1
fi

echo "==> Generating TypeScript types from OpenAPI spec ..."
npx --yes openapi-typescript "$TMP_DIR/spec.json" -o "$SDK_DIR/src/types.ts"

# Prepend a header comment so readers know the file is auto-generated.
HEADER="/**
 * @finchippay/sdk — Auto-generated types from the Finchippay OpenAPI spec.
 *
 * This file is generated by \`npm run generate:sdk\` (openapi-typescript).
 * Do not edit this file directly — edit the OpenAPI spec (backend/src/swagger.js)
 * and regenerate.
 */"

if ! head -1 "$SDK_DIR/src/types.ts" | grep -q "finchippay"; then
  TMP_FILE=$(mktemp)
  echo "$HEADER" > "$TMP_FILE"
  echo "" >> "$TMP_FILE"
  cat "$SDK_DIR/src/types.ts" >> "$TMP_FILE"
  mv "$TMP_FILE" "$SDK_DIR/src/types.ts"
fi

echo "==> SDK types regenerated successfully!"
echo "    File: $SDK_DIR/src/types.ts"
