#!/usr/bin/env bash
#
# scripts/generate-sdk.sh
# Regenerates the TypeScript SDK types from the running backend's OpenAPI spec.
#
# Usage:
#   ./scripts/generate-sdk.sh          # Fetch from localhost:4000
#   API_URL=http://prod.example.com ./scripts/generate-sdk.sh  # Custom URL
#
# Prerequisites:
#   - Backend server must be running (or API_URL must point to a live instance)
#   - openapi-typescript must be installed (via root or npx)
#

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
SDK_DIR="$PROJECT_DIR/sdk"

# Default API URL — override with API_URL env var
API_URL="${API_URL:-http://localhost:4000}"
SPEC_URL="$API_URL/api/docs.json"

echo "==> Fetching OpenAPI spec from $SPEC_URL ..."

# Verify the spec is reachable
if ! curl -sf "$SPEC_URL" > /dev/null 2>&1; then
  echo "ERROR: Cannot reach $SPEC_URL. Is the backend running?"
  echo "  Start it with: cd backend && npm start"
  echo "  Or set API_URL to a running instance."
  exit 1
fi

echo "==> Generating TypeScript types from OpenAPI spec ..."
npx --yes openapi-typescript "$SPEC_URL" -o "$SDK_DIR/src/types.ts"

echo "==> Formatting generated types ..."
# Ensure the generated file has the proper header
if [ -f "$SDK_DIR/src/types.ts" ]; then
  # Prepend a header comment if not already present
  HEADER="/**
 * @finchippay/sdk — Auto-generated types from the Finchippay OpenAPI spec.
 *
 * This file is generated by \`npm run generate:sdk\` (openapi-typescript).
 * Do not edit this file directly — edit the OpenAPI spec (backend/src/swagger.js)
 * and regenerate.
 */"

  # Check if header already exists
  if ! head -1 "$SDK_DIR/src/types.ts" | grep -q "finchippay"; then
    TMP_FILE=$(mktemp)
    echo "$HEADER" > "$TMP_FILE"
    echo "" >> "$TMP_FILE"
    cat "$SDK_DIR/src/types.ts" >> "$TMP_FILE"
    mv "$TMP_FILE" "$SDK_DIR/src/types.ts"
  fi
fi

echo "==> SDK types regenerated successfully!"
echo "    File: $SDK_DIR/src/types.ts"
echo ""
echo "Next steps:"
echo "  cd $SDK_DIR && npm run build   # Build the SDK package"