/**
 * lib/generatePDF.ts
 * Generate PDF receipts for transactions
 */

import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { formatAsset, formatDate } from "@/utils/format";

interface TransactionForPDF {
  hash: string;
  ledger: number;
  createdAt: string;
  sourceAccount: string;
  fee: string;
  memo?: string;
  amount?: string;
  asset?: string;
  from?: string;
  to?: string;
  successful: boolean;
}

/** Type alias exported for components to reference. */
export type TransactionReceipt = TransactionForPDF;

export async function generatePDFReceipt(transaction: TransactionForPDF): Promise<void> {
  const doc = new jsPDF();
  
  // Colors
  const primaryColor: [number, number, number] = [99, 102, 241]; // Stellar blue
  const darkColor: [number, number, number] = [15, 23, 42]; // Dark slate
  const lightColor: [number, number, number] = [148, 163, 184]; // Light slate
  
  // Header - Finchippay branding
  doc.setFillColor(...primaryColor);
  doc.rect(0, 0, 210, 40, "F");
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont("helvetica", "bold");
  doc.text("Finchippay", 20, 25);
  
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text("Transaction Receipt", 20, 33);
  
  // Reset text color for body
  doc.setTextColor(...darkColor);
  
  // Title
  let yPos = 55;
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text("Transaction Details", 20, yPos);
  
  yPos += 10;
  
  // Status badge
  if (transaction.successful) {
    doc.setFillColor(16, 185, 129); // Emerald
    doc.setTextColor(255, 255, 255);
    doc.rect(20, yPos, 30, 8, "F");
    doc.setFontSize(9);
    doc.text("CONFIRMED", 22, yPos + 5.5);
  } else {
    doc.setFillColor(239, 68, 68); // Red
    doc.setTextColor(255, 255, 255);
    doc.rect(20, yPos, 25, 8, "F");
    doc.setFontSize(9);
    doc.text("FAILED", 22, yPos + 5.5);
  }
  
  yPos += 15;
  doc.setTextColor(...darkColor);
  
  // Amount section (if payment)
  if (transaction.amount && transaction.asset) {
    doc.setFillColor(241, 245, 249); // Light gray background
    doc.rect(20, yPos, 170, 25, "F");
    
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...lightColor);
    doc.text("Amount", 25, yPos + 8);
    
    doc.setFontSize(18);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...darkColor);
    doc.text(formatAsset(transaction.amount, transaction.asset), 25, yPos + 18);
    
    yPos += 30;
  }
  
  // Transaction details table
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  
  const tableData = [
    ["Transaction Hash", transaction.hash],
    ["Timestamp", formatDate(transaction.createdAt)],
    ["Ledger", transaction.ledger.toLocaleString()],
    ["Fee Charged", `${transaction.fee} XLM`],
  ];
  
  if (transaction.from) {
    tableData.push(["From", transaction.from]);
  }
  
  if (transaction.to) {
    tableData.push(["To", transaction.to]);
  }
  
  if (transaction.memo) {
    tableData.push(["Memo", transaction.memo]);
  }
  
  // Use autoTable plugin
  autoTable(doc, {
    startY: yPos,
    head: [],
    body: tableData,
    margin: { left: 20, right: 20 },
    styles: {
      fontSize: 9,
      cellPadding: 4,
    },
    columnStyles: {
      0: { fontStyle: "bold", cellWidth: 40 },
      1: { cellWidth: 130 },
    },
    theme: "plain",
  });
  
  // Footer
  const footerY = 270;
  doc.setDrawColor(...lightColor);
  doc.line(20, footerY, 190, footerY);
  
  doc.setFontSize(8);
  doc.setTextColor(...lightColor);
  doc.text("Generated by Finchippay", 20, footerY + 5);
  doc.text(new Date().toLocaleString(), 190, footerY + 5, { align: "right" });
  
  doc.text(
    "This is an official transaction receipt from the Stellar blockchain.",
    105,
    footerY + 10,
    { align: "center" }
  );
  
  // Save the PDF
  const fileName = `finchippay-receipt-${transaction.hash.substring(0, 8)}.pdf`;
  doc.save(fileName);
}